# Generated by Django 3.2 on 2021-04-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_material'),
        ('jwt_auth', '0002_alter_user_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='items.Item'),
        ),
    ]
