# Generated by Django 3.2 on 2021-04-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0004_alter_user_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wishlist',
            new_name='wishlist_items',
        ),
    ]
