# Generated by Django 3.2 on 2021-04-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True, unique=True)),
                ('image_01', models.CharField(max_length=300)),
                ('image_02', models.CharField(max_length=300)),
                ('image_03', models.CharField(blank=True, max_length=300, null=True)),
                ('garment_type', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('price', models.FloatField()),
                ('rrp', models.FloatField()),
                ('colour', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=800)),
            ],
        ),
    ]
