# Generated by Django 3.2 on 2021-04-15 13:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True, unique=True)),
                ('garment_type', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=80)),
                ('size', models.FloatField()),
                ('price', models.FloatField()),
                ('rrp', models.FloatField()),
                ('colour', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None), size=None)),
                ('material', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None), size=None)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
