# Generated by Django 3.2 on 2021-04-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210415_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image01',
            new_name='image_01',
        ),
    ]
