# Generated by Django 3.2 on 2021-04-16 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0002_auto_20210416_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_rental_items',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_rental_items', to='jwt_auth.user'),
            preserve_default=False,
        ),
    ]
