# Generated by Django 3.2 on 2021-04-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_current_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
