# Generated by Django 3.2 on 2021-04-16 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0003_item_current_rental_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='current_rental_items',
        ),
        migrations.AddField(
            model_name='item',
            name='current_renter',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_renter', to='jwt_auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.IntegerField(),
        ),
    ]
